### ISSUE TITLE
Question: Is this intended to run against the same blockchain?

### ISSUE THREAD

**Issue by faddat** [Someguy123/understeem#3]
Thanks, I await your answer, and want you to hear from me:

This is good thinking in action.

**Comment by Someguy123** [comment]
Yes, it is intended to run against the same blockchain.

At the current point in time, there is no real censorship at the blockchain level. Instead, it's most likely that Steemit will put in place filters, e.g. ban the torrents tag, restrict nsfw etc. which will seriously affect the rankings.

Understeem has already removed the first filter, which is NSFW. Soon I expect them to attempt to ban tags such as torrents, or other potentially dangerous tags, which Understeem will NOT be implementing.

**Comment by faddat** [comment]
I've said from the start that steemit potentially represented a better deal for the actors in porn.  By keeping porn around, you're actually helping those who star in it as well as the overall value of the chain.  As for the torrents, well, I have to say that I agree on that front, too:  

It's not possible to have a site (no maybe an anything) that's all about freedom of speech without folks saying some inconvenient things, some of which will of course be said while nude. Such is life.

Rankings of what?  Content?
